# Generated by Django 2.2.4 on 2022-09-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_show_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
