# Generated by Django 2.2.4 on 2022-10-01 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_show_app', '0002_shows_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateTimeField(default=datetime.date(2022, 10, 1)),
        ),
    ]
