# Generated by Django 2.2.4 on 2022-10-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('liker', models.ManyToManyField(related_name='favor', to='login_app.User')),
                ('uploadeder', models.ForeignKey(on_delete='cascade', related_name='uploader', to='login_app.User')),
            ],
        ),
    ]
