# Generated by Django 2.2.4 on 2022-10-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
