# Generated by Django 2.2.4 on 2022-10-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
